Deployment
rsksmart/ri-aggregation pull request #9
Opened 2022-01-26 15:49 UTC by julianlen

I created four different directories within the `env` directory.

testnet/ & mainnet/  -These directories contain the configuration for deployment almost ready on each network. It only needs to set up the private keys. Before deploying on Mainnet, all the variables must be rechecked.

zk/ - It contains the variable as those were on zkSync originally.

2022-01-28 20:21 UTC, raullaprida requested changes
Small comments done.
Also, The purpose of the etc/env/zk folder is not clear to me. /base has the same reference values

2022-01-31 13:24 UTC, julianlen commented on etc/env/mainnet/contracts.toml
> +UPGRADE_GATEKEEPER_ADDR="0x5E6D086F5eC079ADFF4FB3774CDf3e8D6a34F7E9"
Shouldn't be an issue, but change it just in case

2022-01-31 13:38 UTC, julianlen commented on etc/env/mainnet/contracts.toml
> +UPGRADE_GATEKEEPER_ADDR="0x5E6D086F5eC079ADFF4FB3774CDf3e8D6a34F7E9"
These addresses are upgraded when the contracts are deployed

2022-01-31 13:40 UTC, julianlen commented on etc/env/testnet/contracts.toml
> +UPGRADE_GATEKEEPER_ADDR = "0x7389030eDb27924BCe611AdcC1D4b7dbbA2aEc84"
These addresses are upgraded when the contracts are deployed

2022-02-02 19:37 UTC, raullaprida approved these changes
LGTM

2022-02-07 17:05 UTC, merged